### ISSUE TITLE
Request for license change

### ISSUE THREAD

**Issue by skim1420** [davidchambers/Base64.js#19]
We can't redistribute based on WTFPL. Would you be open to changing the license to any of the [http://apache.org/licenses/LICENSE-2.0](Apache 2), [http://opensource.org/licenses/mit-license.php](MIT), [http://opensource.org/licenses/bsd-license.php](BSD), etc?

**Comment by davidchambers** [comment]
Could it be dual-licensed?

**Comment by skim1420** [comment]
Just wanted to let you know I'm checking with our legal, please stand by. And thanks!

**Comment by davidchambers** [comment]
Okay, will do. :)

**Comment by skim1420** [comment]
Dual licensing is fine, thank you. If it's no different, we'd prefer Apache 2 (less variant ambiguity), but any of the others I mentioned would be great too.

**Comment by skim1420** [comment]
I've sent a PR updating the license, for your convenience. Thanks again.

**Comment by skim1420** [comment]
Updated PR per your comments, PTAL.

**Comment by skim1420** [comment]
https://github.com/davidchambers/Base64.js/pull/20
