### ISSUE TITLE
It could be ~3x faster

### ISSUE THREAD

**Issue by duzun** [davidchambers/Base64.js#23]
Compare [this btoa](https://duzun.me/playground/js_speed#c=var%20ret%20%3D%20_btoa('some%20test%20string')&d=console.log(ret)&i=var%20b64%20%3D%20'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%2B%2F%3D'%3B%0Avar%20_btoa%20%3D%20function%20_btoa(data)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(!data)%20return%20data%3B%0Adata%20%3D%20String(data)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20o1%2C%20o2%2C%20o3%2C%20h1%2C%20h2%2C%20h3%2C%20h4%2C%20bits%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2C%20%20%20i%20%3D%200%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2C%20%20%20ac%20%3D%200%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2C%20%20%20enc%20%3D%20''%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2C%20%20%20tmp_arr%20%3D%20%5B%5D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20do%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20pack%20three%20octets%20into%20four%20hexets%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20o1%20%3D%20data.charCodeAt(i%2B%2B)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20o2%20%3D%20data.charCodeAt(i%2B%2B)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20o3%20%3D%20data.charCodeAt(i%2B%2B)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20bits%20%3D%20o1%20%3C%3C%2016%20%7C%20o2%20%3C%3C%208%20%7C%20o3%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20h1%20%3D%20bits%20%3E%3E%2018%20%26%200x3f%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20h2%20%3D%20bits%20%3E%3E%2012%20%26%200x3f%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20h3%20%3D%20bits%20%3E%3E%206%20%26%200x3f%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20h4%20%3D%20bits%20%26%200x3f%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20use%20hexets%20to%20index%20into%20b64%2C%20and%20append%20result%20to%20encoded%20string%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20tmp_arr%5Bac%2B%2B%5D%20%3D%20b64.charAt(h1)%20%2B%20b64.charAt(h2)%20%2B%20b64.charAt(h3)%20%2B%20b64.charAt(h4)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%20while%20(i%20%3C%20data.length)%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20enc%20%3D%20tmp_arr.join('')%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20r%20%3D%20data.length%20%25%203%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20(r%20%3F%20enc.slice(0%2C%20r%20-%203)%20%3A%20enc)%20%2B%20'%3D%3D%3D'.slice(r%20%7C%7C%203)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A&n=100000) improved implementation with [yours](https://duzun.me/playground/js_speed#c=var%20ret%20%3D%20_btoa('some%20test%20string')&d=console.log(ret)&i=var%20chars%20%3D%20'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%2B%2F%3D'%3B%0A%0A%20%20function%20InvalidCharacterError(message)%20%7B%0A%20%20%20%20this.message%20%3D%20message%3B%0A%20%20%7D%0A%20%20InvalidCharacterError.prototype%20%3D%20new%20Error%3B%0A%20%20InvalidCharacterError.prototype.name%20%3D%20'InvalidCharacterError'%3B%0A%0Avar%20_btoa%20%3D%20function%20(input)%20%7B%0A%20%20%20%20var%20str%20%3D%20String(input)%3B%0A%20%20%20%20for%20(%0A%20%20%20%20%20%20%2F%2F%20initialize%20result%20and%20counter%0A%20%20%20%20%20%20var%20block%2C%20charCode%2C%20idx%20%3D%200%2C%20map%20%3D%20chars%2C%20output%20%3D%20''%3B%0A%20%20%20%20%20%20%2F%2F%20if%20the%20next%20str%20index%20does%20not%20exist%3A%0A%20%20%20%20%20%20%2F%2F%20%20%20change%20the%20mapping%20table%20to%20%22%3D%22%0A%20%20%20%20%20%20%2F%2F%20%20%20check%20if%20d%20has%20no%20fractional%20digits%0A%20%20%20%20%20%20str.charAt(idx%20%7C%200)%20%7C%7C%20(map%20%3D%20'%3D'%2C%20idx%20%25%201)%3B%0A%20%20%20%20%20%20%2F%2F%20%228%20-%20idx%20%25%201%20*%208%22%20generates%20the%20sequence%202%2C%204%2C%206%2C%208%0A%20%20%20%20%20%20output%20%2B%3D%20map.charAt(63%20%26%20block%20%3E%3E%208%20-%20idx%20%25%201%20*%208)%0A%20%20%20%20)%20%7B%0A%20%20%20%20%20%20charCode%20%3D%20str.charCodeAt(idx%20%2B%3D%203%2F4)%3B%0A%20%20%20%20%20%20if%20(charCode%20%3E%200xFF)%20%7B%0A%20%20%20%20%20%20%20%20throw%20new%20InvalidCharacterError(%22'btoa'%20failed%3A%20The%20string%20to%20be%20encoded%20contains%20characters%20outside%20of%20the%20Latin1%20range.%22)%3B%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20block%20%3D%20block%20%3C%3C%208%20%7C%20charCode%3B%0A%20%20%20%20%7D%0A%20%20%20%20return%20output%3B%0A%20%20%7D%3B&n=100000).

There is space for better performance!

Cheers

**Comment by davidchambers** [comment]
Pull requests welcome. :)

**Comment by Mouvedia** [comment]
This should be reopened.

**Comment by davidchambers** [comment]
I'll happily review a pull request if you submit one, @Mouvedia. :)
