### ISSUE TITLE
How to handle InvalidCharacterError?

### ISSUE THREAD

**Issue by volkanunsal** [davidchambers/Base64.js#25]
I started using this library as an alternative to `atob` in Safari. It handles more cases than the native implementation, but I still run into this error occasionally. It doesn't tell me which character is causing the problem, and I don't know how to handle it. What can be done to make `atob` more robust?

**Comment by davidchambers** [comment]
Could you provide example input for which `atob` throws an InvalidCharacterError?

**Comment by volkanunsal** [comment]
I had an issue with this yesterday, but the user edited the page today and the offending characters are gone, and it started to work again. I'm going to update this issue if I see that error again.

**Comment by davidchambers** [comment]
Okay. Sounds good. :)
