### ISSUE TITLE
assigning this does not work in all environments

### ISSUE THREAD

**Issue by ChristianUlbrich** [davidchambers/Base64.js#26]
Hi,

the code:
```
var object = typeof exports != 'undefined' ? exports : this; // #8: web workers
  var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';
```
does rely on the fact, that `this` is always referring to the global scope; but when somehow base64 is evaluated in other contexts, `this` can be undefined and thus the subsequent assigning of btoa is failing, because `object` itself is then undefined.

When using the grunt usemin task for production, we get this error in the production build. There is no easy way around it; maybe one could check simply, whether `atob` `btoa` itself is a function, when `exports` is undefined.

**Comment by michaelficarra** [comment]
This is the most reliable way I've found to get the global object: https://gist.github.com/michaelficarra/791f9742ca95318278a63f82c536e564.

**Comment by ChristianUlbrich** [comment]
Personally I would not even bother, either polyfill atob / btoa for a "global" `window`or attach them to the global `exports`. Of course, when someone abused window or exports you are out of luck, but some crimes deserve to be punished :)

**Comment by davidchambers** [comment]
We had

```javascript
typeof exports != 'undefined' ? exports : window
```

initially, but switched to

```javascript
typeof exports != 'undefined' ? exports : this
```

in #8 to support web workers.

> when somehow base64 is evaluated in other contexts, `this` can be undefined

Perhaps an error in your build pipeline is resulting in this module being run in strict mode. That's one explanation for `this` being `undefined`:

```javascript
> (function() { return this === window; }())
true

> (function() { 'use strict'; return this === undefined; }())
true
```

**Comment by michaelficarra** [comment]
@davidchambers If you don't want to use my heavy weight approach, `self` should work in all "browser" contexts.

**Comment by ChristianUlbrich** [comment]
@davidchambers Still if the specific use case is about supporting web workers, there should be a specific way to get hold of their global object.

The "error in my build pipeline" is using the stock grunt _usemin_ plugin, if I were to use the same library with WebPack it would be the same result - it also enforces strict mode.

I would not write code, that relies on being run in non-strict mode, so yeah basically this is why the error comes up.

**Comment by davidchambers** [comment]
> Still if the specific use case is about supporting web workers, there should be a specific way to get hold of their global object.

As Michael mentioned, replacing `this` with `self` should do the trick. I'll make this change.

> The "error in my build pipeline" is using the stock grunt _usemin_ plugin, if I were to use the same library with WebPack it would be the same result - it also enforces strict mode.

I didn't realize these tools are only compatible with modules which work correctly in strict mode. This strikes me as an unfortunate limitation.

Making the module work correctly in both modes seems ideal.

**Comment by ChristianUlbrich** [comment]
_Every serious_ project I have been working on is using strict mode and for good reasons. Hell without strict mode you won't get any ES6 features in NodeJS whatsoever. Code linting / hinting fails in our projects, when strict mode is not used.

Every major JS style guide, recommends using strict mode.

I do not see a use case for serious JS projects without using strict mode - well at least not for me and my company. Not using strict mode allows all kind of crazy stuff - `this` referring to the global object is only the tip of the ice berg.

**Comment by davidchambers** [comment]
I absolutely agree that we should opt in to strict mode for new projects.

My point is that tools should not dictate what is and isn't acceptable JavaScript code unless there's something significant to be gained by doing so (and perhaps there is).
