### ISSUE TITLE
Adobe ExtendScript errors with self and certain regular expressions

### ISSUE THREAD

**Issue by SheetJSDev** [davidchambers/Base64.js#31]
We were addressing an unexpected issue about running in Adobe ExtendScript https://github.com/SheetJS/js-xlsx/issues/603. 
 It's the scripting runtime for Adobe products, and it claims to be "extended" ECMAScript. 

After some digging, we found two issues:

1) `self` is not available in extendscript and the object assignment assumes `self` is defined:

```js
  var object = typeof exports != 'undefined' ? exports : self; // #8: web workers
  // when exports and self are both undefined, this line fails thanks to the unguarded assignment 
```

The indirect eval trick `(1,eval)('this')` appeared to work:
```js
  var object = typeof exports != 'undefined' ? exports : typeof self != 'undefined' ? self : (1,eval)('this')
```

2) Regular expression literals starting with `=` are problematic:

<img width="198" alt="screen shot 2017-03-23 at 19 32 44" src="https://cloud.githubusercontent.com/assets/6070939/24274581/8ce50c70-0fff-11e7-962f-56ab6509dea0.png">

I believe the fix here is to turn `/=+$/` into a RegExp call: `new RegExp("=+$")`

**Comment by davidchambers** [comment]
Would you like to submit a pull request?

**Comment by SheetJSDev** [comment]
I'm confident that the aforementioned fixes will work in IE6+, and I think I understand why they fail in the first place: in the first case the global variable is not available, and in the second case, there's a parse ambiguity wherein ExtendScript treats $ as a special variable, so it sees `/=+$/` as a division-assignment for the value `+$/...`).

However there are two things that are not clear:

1) What environments support `Base64.js`?  Is it just "whatever happens to work" or do you have a specific target (e.g. IE6+) in mind? 

2) how do you test in the supported environments?  I see a coffeescript test script -- do you manually generate the JS for it and add it to an HTML page?  Do you use the mocha skeleton?

**Comment by davidchambers** [comment]
We'd like this package to work in as many environments as possible. The test suite only runs in Node so doesn't tell us whether the package works in other environments.

The approach I'm taking with this package is to make the smallest possible changes only when absolutely necessary. In lieu of a comprehensive test suite we rely on our reasoning abilities. As a result, changes should be small and well documented.

Does parenthesizing the regexp literal fix that problem? If so, let's go with that change. :)

**Comment by SheetJSDev** [comment]
The second change is replacing the literal regexp syntax with the constructor form: `new RegExp("=+$")` rather than `/=+$/`.  The RegExp constructor was introduced in ES3; I don't know when the regexp literals were introduced but it's likely ES3 as well.

**Comment by davidchambers** [comment]
Is it possible to use ExtendScript on macOS without installing Creative Cloud?

**Comment by SheetJSDev** [comment]
The latest version unfortunately requires a CC account, but the CS5 ExtendScript toolkit is available at https://www.adobe.com/devnet/scripting/estk.html and you don't need to register to download.  The OSX version is http://download.macromedia.com/pub/developer/estk/sdk/AdobeExtendScriptToolkit3.5.0-mul.dmg

**Comment by michaelficarra** [comment]
You can use the empty non-capturing group: `/(?:)=+$/`
